databases:
  - name: idle3_DB
    databaseName: idle3_db
    user: idle3
    region: singapore

services:
  - type: web
    name: idle3
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: idle3_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false